### ISSUE TITLE
CI websiteが落ちている

### ISSUE THREAD

**Issue by massongit** [textlint-ja/textlint-rule-preset-JTF-style#136]
https://github.com/textlint-ja/textlint-rule-preset-JTF-style/actions/runs/12106677543/job/33752694582

<details>

```
> textlint-website-generator --output-dir dist --metadataVersion=2.3.14

[
  {
    moduleIdentifier: 'node:os',
    moduleName: 'node:os',
    message: 'Module build failed: UnhandledSchemeError: Reading from "node:os" is not handled by plugins (Unhandled scheme).\n' +
      'Webpack supports "data:" and "file:" URIs by default.\n' +
      'You may need an additional plugin to handle "node:" URIs.\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:973:10\n' +
      '    at Hook.eval [as callAsync] (eval at create (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Object.processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:969:8)\n' +
      '    at processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:397:2)\n' +
      '    at NormalModule._doBuild (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:959:3)\n' +
      '    at NormalModule.build (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:1144:15)\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/Compilation.js:1418:12\n' +
      '    at NormalModule.needBuild (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:1466:32)',
    moduleId: 8[16](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/actions/runs/12106677543/job/33752694582#step:6:17)5,
    moduleTrace: [ [Object], [Object], [Object], [Object] ],
    details: undefined,
    stack: 'ModuleBuildError: Module build failed: UnhandledSchemeError: Reading from "node:os" is not handled by plugins (Unhandled scheme).\n' +
      'Webpack supports "data:" and "file:" URIs by default.\n' +
      'You may need an additional plugin to handle "node:" URIs.\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:973:10\n' +
      '    at Hook.eval [as callAsync] (eval at create (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Object.processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:969:8)\n' +
      '    at processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:[17](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/actions/runs/12106677543/job/33752694582#step:6:18)1:10)\n' +
      '    at runLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:397:2)\n' +
      '    at NormalModule._doBuild (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:959:3)\n' +
      '    at NormalModule.build (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:1144:15)\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/Compilation.js:14[18](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/actions/runs/12106677543/job/33752694582#step:6:19):12\n' +
      '    at NormalModule.needBuild (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:1466:32)\n' +
      '    at processResult (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:885:[19](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/actions/runs/12106677543/job/33752694582#step:6:20))\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:1026:5\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:399:11\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:221:19\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:972:16\n' +
      '    at Hook.eval [as callAsync] (eval at create (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Object.processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:969:8)\n' +
      '    at processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:2[20](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/actions/runs/12106677543/job/33752694582#step:6:21):11)\n' +
      '    at iteratePitchingLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:397:2)',
    compilerPath: undefined
  },
  {
    moduleIdentifier: 'node:path',
    moduleName: 'node:path',
    message: 'Module build failed: UnhandledSchemeError: Reading from "node:path" is not handled by plugins (Unhandled scheme).\n' +
      'Webpack supports "data:" and "file:" URIs by default.\n' +
      'You may need an additional plugin to handle "node:" URIs.\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:973:10\n' +
      '    at Hook.eval [as callAsync] (eval at create (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/tapable/lib/Hook.js:18:14)\n' +
      '    at Object.processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:969:8)\n' +
      '    at processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:397:2)\n' +
      '    at NormalModule._doBuild (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:959:3)\n' +
      '    at NormalModule.build (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:1144:15)\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/Compilation.js:1418:12',
    moduleId: 498,
    moduleTrace: [ [Object], [Object], [Object], [Object] ],
    details: undefined,
    stack: 'ModuleBuildError: Module build failed: UnhandledSchemeError: Reading from "node:path" is not handled by plugins (Unhandled scheme).\n' +
      'Webpack supports "data:" and "file:" URIs by default.\n' +
      'You may need an additional plugin to handle "node:" URIs.\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:973:10\n' +
      '    at Hook.eval [as callAsync] (eval at create (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/tapable/lib/Hook.js:18:14)\n' +
      '    at Object.processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:969:8)\n' +
      '    at processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:397:2)\n' +
      '    at NormalModule._doBuild (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:959:3)\n' +
      '    at NormalModule.build (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:1144:15)\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/Compilation.js:1418:12\n' +
      '    at processResult (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:885:19)\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:1026:5\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:399:11\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:2[21](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/actions/runs/12106677543/job/33752694582#step:6:22):19\n' +
      '    at /home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:972:16\n' +
      '    at Hook.eval [as callAsync] (eval at create (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/tapable/lib/Hook.js:18:14)\n' +
      '    at Object.processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/webpack/lib/NormalModule.js:969:8)\n' +
      '    at processResource (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:[22](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/actions/runs/12106677543/job/33752694582#step:6:23)0:11)\n' +
      '    at iteratePitchingLoaders (/home/runner/work/textlint-rule-preset-JTF-style/textlint-rule-preset-JTF-style/example/node_modules/loader-runner/lib/LoaderRunner.js:171:10)',
    compilerPath: undefined
  }
]
```

</details>

https://github.com/textlint-ja/textlint-rule-preset-JTF-style/pull/134 ( https://github.com/textlint-ja/textlint-rule-preset-JTF-style/commit/4e2b211c85f99d6f7a0505a954c93c25123a9779 ) 以降、CI `website` が落ちているようです。

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-preset-JTF-style/commit/15e30bbc54e6678f947459081cdc8c97d08e9c18 で修正しました
